Feat/onboard hv b
clio-finance/official-spells-goerli pull request #4
Opened 2022-06-22 13:12 UTC by nduchak

# Description

# Contribution Checklist

- [ ] PR title starts with `(PE-<TICKET_NUMBER>)`
- [ ] Code approved
- [ ] Tests approved
- [ ] CI Tests pass

# Checklist

- [ ] Every contract variable/method declared as public/external private/internal
- [ ] Consider if this PR needs the `officeHours` modifier override
- [ ] Verify expiration (`30 days` unless otherwise specified)
- [ ] Verify hash in the description matches [here](https://emn178.github.io/online-tools/keccak_256.html)
- [ ] Validate all addresses used are in Goerli changelog or known
- [ ] Notify any external teams affected by the spell so they have the opportunity to review
- [ ] Deploy spell to Goerli `ETH_GAS="XXX" ETH_GAS_PRICE="YYY" make deploy`
- [ ] Ensure contract is verified on `Goerli` etherscan
- [ ] Change test to use Goerli spell address and deploy timestamp
- [ ] Cast spell on Goerli `make spell="0x-deployed-spell-address" cast-spell`
- [ ] Run `make archive-spell` or `make date="YYYY-MM-DD" archive-spell` to make an archive directory and copy `Goerli-DssSpell.sol`, `Goerli-DssSpell.t.sol`, `Goerli-DssSpell.t.base.sol`, and `Goerli-DssSpellCollateralOnboarding.sol`
- [ ] `squash and merge` this PR

2022-07-04 12:30 UTC, nduchak commented
[sc-832]

2022-07-04 13:40 UTC, hbarcelos requested changes
We should probably remove the `AT1` suffix from the official spell.

2022-07-06 13:10 UTC, hbarcelos commented on src/test/config.sol
> +        afterSpell.collaterals["RWA009AT1-A"] = CollateralValues({
```suggestion
        afterSpell.collaterals["RWA009-A"] = CollateralValues({
```

2022-07-06 13:12 UTC, hbarcelos requested changes
There's still lots of references to `RWA009AT1` that should be changed to `RWA009`.

2022-07-06 13:25 UTC, dbkbali requested changes
Good work Naz will rereview when you push changes

2022-07-06 13:25 UTC, dbkbali commented on src/Goerli-DssSpell.t.sol
> +        checkChainlogKey("MCD_JOIN_RWA009AT1_A");
Naz assuming this will be adjusted when you address @hbarcelos comment above

2022-07-06 16:42 UTC, hbarcelos approved these changes
LGTM

2022-07-07 12:56 UTC, dbkbali commented on src/Goerli-DssSpellCollateralOnboarding.sol
> +    address constant RWA009_A_OUTPUT_CONDUIT  = 0x7a3D23Dc73F7ead55399597aAE6e525b3DF95A88;
Noting that this address is not Genesis Public address - maybe we should add a comment here so we dont forget to change it on mainnet

2022-07-07 13:01 UTC, dbkbali approved these changes
Great work @nduchak

2022-07-11 12:27 UTC, hbarcelos approved these changes

2022-07-18 15:14 UTC, hbarcelos commented on src/Goerli-DssSpellCollateral.sol
> +        onboardRwa008(CHANGELOG, REGISTRY, MIP21_LIQUIDATION_ORACLE, MCD_VAT, MCD_JUG, MCD_SPOT);
As we talked about it in earlier today, maybe we should keep the logical order here and onboard `RWA008` before `RWA009`.
Don't forget to update the tests (:

2022-07-18 15:15 UTC, hbarcelos reviewed
LGTM overall, just some small changes that we've discussed on the call earlier today.

2022-07-19 14:54 UTC, merged